
FROM ubuntu
RUN apt-get update
RUN apt-get install -y docker-compose libmemcached-dev gcc python-dev

FROM python:3
RUN mkdir
WORKDIR
COPY requirements.txt
RUN pip install -r requirements.txt

RUN docker-compose up -d